kind: Service
apiVersion: v1
metadata:
  name: oracle-digitalassistant-hnb-component-service
  labels:
    app: oracle-digitalassistant-hnb-component
spec:
  type: LoadBalancer
  selector:
    app: oracle-digitalassistant-hnb-component
  ports:
  - port: 80
    targetPort: 3000
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: oracle-digitalassistant-hnb-component-deployment
  labels:
    app: oracle-digitalassistant-hnb-component
spec:
  selector:
    matchLabels:
      app: oracle-digitalassistant-hnb-component
  replicas: 1
  template:
    metadata:
      labels:
        app: oracle-digitalassistant-hnb-component
        version: v1
    spec:
      containers:
      - name: oracle-digitalassistant-hnb-component
        image: 'eu-frankfurt-1.ocir.io/oraseemeaceeociworkshop/ivandelic/zaba/digitalassistant-hnb-component:latest'
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: OBP_RESTPROXY1_USERNAME
            valueFrom:
              secretKeyRef:
                name: obp-restproxy1
                key: username
          - name: OBP_RESTPROXY1_PASSWORD
          valueFrom:
            secretKeyRef:
              name: obp-restproxy1
              key: password
      imagePullSecrets:
      - name: ocirsecret
---
